export const MODEL_SOURCES = {
  ak: "bolt_action_rifle_7_62",
  usp: "service_pistol",
  knife: "machete",
  mol: "bleach_bottle",
  barrel: "Barrel_01",
  lantern: "Lantern_01",
  planter: "planter_box_01",
  succulent: "cheiridopsis_succulent",
  shrub: "didelta_spinosa",
  crate: "old_military_crate",
  crate2: "plastic_crate_01",
  rockset: "rock_moss_set_01",
  boulder: "namaqualand_boulder_04",
  fern: "fern_02",
  stump: "tree_stump_01",
  dtree: "quiver_tree_01",
  deadtree: "dead_tree_trunk",
  toolbox: "metal_toolbox",
  desk: "metal_office_desk",
  chair: "SchoolChair_01",
  pplant: "potted_plant_01",
  cabinet: "drawer_cabinet",
  sofa: "Sofa_01",
  bookshelf: "wooden_bookshelf_worn",
  trashcan: "metal_trash_can",
  extinguisher: "korean_fire_extinguisher_01",
  cofftable: "modern_coffee_table_01",
  cardbox: "cardboard_box_01",
  pplant2: "potted_plant_02",
  clock: "wall_clock",
  treebig: "island_tree_01",
  treemed: "island_tree_02",
  cliff: "coastal_cliff_04",
  rockset2: "rock_moss_set_02",
  tropplant: "pachira_aquatica_01",
  leafplant: "calathea_orbifolia_01",
} as const;

export type ModelId = keyof typeof MODEL_SOURCES;

export const ACTIVE_MODEL_IDS: ModelId[] = [
  "ak",
  "usp",
  "knife",
  "mol",
  "barrel",
  "lantern",
  "planter",
  "succulent",
  "shrub",
  "crate",
  "boulder",
  "dtree",
  "toolbox",
  "desk",
  "chair",
  "pplant",
  "cabinet",
  "sofa",
  "bookshelf",
  "trashcan",
  "extinguisher",
  "cofftable",
  "cardbox",
  "pplant2",
  "clock",
];

export const ACTIVE_HDRI_ASSETS = [
  "assets/hdri/sky.hdr",
  "assets/hdri/shanghai_bund.hdr",
] as const;

export const DEPLOY_PUBLIC_ASSETS = [
  "logo.png",
  "assets/audio",
  "assets/textures",
  ...ACTIVE_HDRI_ASSETS,
  ...ACTIVE_MODEL_IDS.map((id) => `assets/models/${MODEL_SOURCES[id]}`),
] as const;
